# Generated by Django 4.2.1 on 2023-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddat', '0002_role_remove_jobrole_job_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
